### ISSUE TITLE
It runs so slow, switching a parameter, the upper right corner runs halfway through

### ISSUE THREAD

**Issue by jokero3answer** [banodoco/Dough#122]

**Comment by piyushK52** [comment]
where are you running this and in which screen are you switching parameters ?

**Comment by jokero3answer** [comment]
I still like our program very much, but every time I choose an option or modify a parameter, the upper right corner will turn half a day, the experience is very bad, is it because my computer is not enough configuration?
![微信截图_20240415120845](https://github.com/banodoco/Dough/assets/130854108/a08a4ef7-4cd6-4647-a549-005ae11ea0e3)
![微信截图_20240415122904](https://github.com/banodoco/Dough/assets/130854108/cfb6b1fa-ae5a-44f2-974d-b71e3a402949)

**Comment by peteromallet** [comment]
> I still like our program very much, but every time I choose an option or modify a parameter, the upper right corner will turn half a day, the experience is very bad, is it because my computer is not enough configuration? ![微信截图_20240415120845](https://private-user-images.githubusercontent.com/130854108/322352910-a08a4ef7-4cd6-4647-a549-005ae11ea0e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDQ4OTUsIm5iZiI6MTcxMzIwNDU5NSwicGF0aCI6Ii8xMzA4NTQxMDgvMzIyMzUyOTEwLWEwOGE0ZWY3LTRjZDYtNDY0Ny1hNTQ5LTAwNWFlMTFlYTBlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxODA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTU5NzBmMWI4NjNmNmQzNjk2ODc4NTJjZmQ5NzM3M2ZmMzQyNTZhMjRkZjAyZTY3NjI2MTgxZGYxMWFjZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oepzu5gPZ0W_O1rg0BeUX2Af8k8qGzUq3qzYCJhcYlc) ![微信截图_20240415122904](https://private-user-images.githubusercontent.com/130854108/322352914-cfb6b1fa-ae5a-44f2-974d-b71e3a402949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDQ4OTUsIm5iZiI6MTcxMzIwNDU5NSwicGF0aCI6Ii8xMzA4NTQxMDgvMzIyMzUyOTE0LWNmYjZiMWZhLWFlNWEtNDRmMi05NzRkLWI3MWUzYTQwMjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxODA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmMwZmJlYjAxNWMzOGNkNWEzMmYzNzc5NjM5ZGQ1NWM3OGE1Y2UyM2MwY2FlN2NlMzY3ODYxZmQ5ZDMyZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wxXIxOBGzukVln7xFUksG8ejsM3b6YTr2M2lI0kyA7c)

Are you running in on your local machine? What kind of specs do you have? It should be very fast - maybe try reinstall it? It's possible something is misconfigured
