### ISSUE TITLE
CalledProcessError: Command '['git', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by curlysasha** [banodoco/Dough#126]
![image](https://github.com/banodoco/Dough/assets/116119767/b32806f8-4c61-4ca2-bf51-dac85cb61eff)

`C:\GIT\Dough>call dough-env\Scripts\activate

(dough-env) C:\GIT\Dough>scripts\entrypoint.bat

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:5500
  Network URL: http://192.168.1.140:5500

INFO:app_logger:Starting runner
runner running
INFO:app_logger:Database not found. Creating new one.
DEBUG:app_logger:db creation pending..
INFO:app_logger:Migrations completed successfully
INFO:app_logger:new temp user created: banodoco_user
{'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'replicate_key': '', 'replicate_username': '', 'welcome_state': 0}
{'name': 'my_first_project', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02'}
{'name': 'fbd793de-5028-47d3-a046-36d6a7482b45', 'type': 'image', 'local_path': 'videos/330d7147-fe6e-4ae0-8183-598da016990f/resources/prompt_images/c8214bd8-32f7-41c7-92f5-42ffdba2855e.png', 'project_id': '330d7147-fe6e-4ae0-8183-598da016990f', 'shot_uuid': '', 'inference_log_id': None}
{'source_image_id': 'ea5c6757-78c2-43ff-9831-f7a91f043ead', 'shot_id': '326468c1-3b5d-4acf-949a-e268e8d25e5d', 'aux_frame_index': 0}
{'name': 'ae859016-a52d-4d3e-bb86-b3e757a60ce8', 'type': 'image', 'local_path': 'videos/330d7147-fe6e-4ae0-8183-598da016990f/resources/prompt_images/15153f5e-d459-4151-8a45-fac48ad2c007.png', 'project_id': '330d7147-fe6e-4ae0-8183-598da016990f', 'shot_uuid': '', 'inference_log_id': None}
{'source_image_id': '7d4f5b8e-7256-4cd4-b175-dc106a399227', 'shot_id': '326468c1-3b5d-4acf-949a-e268e8d25e5d', 'aux_frame_index': 1}
{'name': 'd3467819-59cc-48ff-a3ba-36ebb79d8499', 'type': 'image', 'local_path': 'videos/330d7147-fe6e-4ae0-8183-598da016990f/resources/prompt_images/d330acec-81d7-4699-b537-020b2b2649a7.png', 'project_id': '330d7147-fe6e-4ae0-8183-598da016990f', 'shot_uuid': '', 'inference_log_id': None}
{'source_image_id': '27a0f545-3a34-42ca-bf54-02b84d77475d', 'shot_id': '326468c1-3b5d-4acf-949a-e268e8d25e5d', 'aux_frame_index': 2}
{'name': 'controlnet', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': None, 'replicate_url': '', 'diffusers_url': '', 'training_image_list': '', 'category': 'controlnet', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'Dreambooth', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': None, 'replicate_url': '', 'diffusers_url': '', 'training_image_list': '', 'category': 'Dreambooth', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'LoRA', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': None, 'replicate_url': '', 'diffusers_url': '', 'training_image_list': '', 'category': 'LoRA', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'urpm-v1.3', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': '4df956e8dbfebf1afaf0c3ee98ad426ec58c4262d24360d054582e5eab2cb5f6', 'replicate_url': 'mcai/urpm-v1.3-img2img', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'stable_diffusion_xl', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': 'af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33', 'replicate_url': 'stability-ai/sdxl', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["txt2img", "img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'realistic_vision_5', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': 'c0259010b93e7a4102a4ba946d70e06d7d0c7dc007201af443cfc8f943ab1d3c', 'replicate_url': 'heedster/realistic-vision-v5', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["txt2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'deliberate_v3', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': '1851b62340ae657f05f8b8c8a020e3f9a46efde9fe80f273eef026c0003252ac', 'replicate_url': 'pagebrain/deliberate-v3', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["txt2img", "img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'dreamshaper_v7', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': '0deba88df4e49b302585e1a7b6bd155e18962c1048966a40fe60ba05805743ff', 'replicate_url': 'pagebrain/dreamshaper-v7', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["txt2img", "img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'epic_realism_v5', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': '222465e57e4d9812207f14133c9499d47d706ecc41a8bf400120285b2f030b42', 'replicate_url': 'pagebrain/epicrealism-v5', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["txt2img", "img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'sdxl_controlnet', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': 'db2ffdbdc7f6cb4d6dab512434679ee3366ae7ab84f89750f8947d5594b79a47', 'replicate_url': 'lucataco/sdxl-controlnet', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'sdxl_controlnet_openpose', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': 'd63e0b238b2d963d90348e2dad19830fbe372a7a43d90d234b2b63cae76d4397', 'replicate_url': 'lucataco/sdxl-controlnet-openpose', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'name': 'realistic_vision_img2img', 'user_id': '0b771c2f-cf58-45cf-bc01-6f2e3a735e02', 'custom_trained': False, 'version': '82bbb4595458d6be142450fc6d8c4d79c936b92bd184dd2d6dd71d0796159819', 'replicate_url': 'lucataco/realistic-vision-v5-img2img', 'diffusers_url': '', 'training_image_list': '', 'category': 'Base_SD', 'keyword': '', 'model_type': '["img2img"]'}
0b771c2f-cf58-45cf-bc01-6f2e3a735e02
{'project_id': '330d7147-fe6e-4ae0-8183-598da016990f', 'default_model_id': 'fc34d7a5-fe81-45b8-af07-7e54953b66bc', 'input_type': 'video', 'width': 512, 'height': 512}
2024-04-19 23:35:45.318 Uncaught app exception
Traceback (most recent call last):
  File "C:\GIT\Dough\dough-env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "C:\GIT\Dough\app.py", line 116, in <module>
    raise e
  File "C:\GIT\Dough\app.py", line 113, in <module>
    main()
  File "C:\GIT\Dough\app.py", line 95, in main
    check_for_updates() # enabling auto updates only for local version
  File "C:\GIT\Dough\utils\app_update_utils.py", line 25, in check_for_updates
    remote_version = get_remote_version()
  File "C:\GIT\Dough\utils\app_update_utils.py", line 135, in get_remote_version
    completed_process = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], check=True, capture_output=True, text=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.`

**Comment by piyushK52** [comment]
You most probably don't have git installed on your system.. You will need to install it before setting up this app. (you can check some YouTube tutorials on how to do it, it should be pretty straightforward)

**Comment by piyushK52** [comment]
@curlysasha  circling back on this, can you try setting up the app from scratch? we have pushed a new update. If that doesn't work then comment out these lines in the code and restart. Hope this resolves the issue!
![Screenshot 2024-05-04 at 7 50 59 AM](https://github.com/banodoco/Dough/assets/34690994/3751b7e0-f9bd-47ae-a86c-7a96f41f9f4f)

**Comment by curlysasha** [comment]
> @curlysasha circling back on this, can you try setting up the app from scratch? we have pushed a new update. If that doesn't work then comment out these lines in the code and restart. Hope this resolves the issue! ![Screenshot 2024-05-04 at 7 50 59 AM](https://private-user-images.githubusercontent.com/34690994/327912063-3751b7e0-f9bd-47ae-a86c-7a96f41f9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODk3ODIsIm5iZiI6MTcxNDc4OTQ4MiwicGF0aCI6Ii8zNDY5MDk5NC8zMjc5MTIwNjMtMzc1MWI3ZTAtZjliZC00N2FlLWE4NmMtN2E5NmY0MWY5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAyMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjlkY2JhODQwODg3OGM3ZDJjMzA5ZWU1YmViNTYzMjRmMDhhZDU4MDY2OTA5NDQyMTY3M2RhMzhiYmNiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y3sMA5qy_gtlZBnE6mIc_jDT5bDFxz4Ygecm514bQqM)

I have solve issue next day, i'm reinstall git
