### ISSUE TITLE
django.db.utils.OperationalError: unable to open database file (with Runpod)

### ISSUE THREAD

**Issue by Jamieharley** [banodoco/Dough#128]
When i run it with Runpod : 

Traceback (most recent call last):
  File "/Dough/dough-env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/Dough/app.py", line 116, in <module>
    raise e
  File "/Dough/app.py", line 113, in <module>
    main()
  File "/Dough/app.py", line 105, in main
    setup_app_ui()
  File "/Dough/ui_components/setup.py", line 97, in setup_app_ui
    data_repo.update_app_setting(previous_project_id=st.session_state['project_uuid'])
  File "/Dough/utils/cache/cache_methods.py", line 442, in _cache_update_app_setting
    status = original_func(self, *args, **kwargs)
  File "/Dough/utils/data_repo/data_repo.py", line 357, in update_app_setting
    res = self.db_repo.update_app_setting(**kwargs)
  File "/Dough/backend/db_repo.py", line 1080, in update_app_setting
    app_setting.save()
  File "/Dough/backend/models.py", line 395, in save
    super(AppSetting, self).save(*args, **kwargs)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/base.py", line 990, in _save_table
    updated = self._do_update(
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1982, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 616, in execute
    return real_execute(self, sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: unable to open database file

**Comment by piyushK52** [comment]
From the error I feel like the installation was not properly completed (or maybe interrupted mid-way).. can you do a fresh install and check?

**Comment by Jamieharley** [comment]
Just did a fresh install. Everything seems fine with the installation, it's when I add to queue a generation : it downloads ip adaptors, checkpoint, etc. and then I have this : 



## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', 'install.py']
                         Collecting opencv-contrib-python
   Downloading opencv_contrib_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68.3 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.3/68.3 MB 47.3 MB/s eta 0:00:00
  Installing collected packages: opencv-contrib-python
 Successfully installed opencv-contrib-python-4.9.0.80
                                                      [!] WARNING: Skipping cupy-wheel as it is not installed.
[!] WARNING: Skipping cupy-cuda102 as it is not installed.
[!] WARNING: Skipping cupy-cuda110 as it is not installed.
[!] WARNING: Skipping cupy-cuda111 as it is not installed.
[!] WARNING: Skipping cupy-cuda11x as it is not installed.
[!] WARNING: Skipping cupy-cuda12x as it is not installed.
 Collecting cupy-wheel
   Downloading cupy-wheel-12.3.0.tar.gz (2.9 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'
 Collecting cupy-cuda11x==12.3.0
   Downloading cupy_cuda11x-12.3.0-cp310-cp310-manylinux2014_x86_64.whl (89.4 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 MB 8.2 MB/s eta 0:00:00
  Collecting fastrlock>=0.5
   Downloading fastrlock-0.8.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_28_x86_64.whl (51 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 KB 14.5 MB/s eta 0:00:00
 Using legacy 'setup.py install' for cupy-wheel, since package 'wheel' is not installed.
 Installing collected packages: fastrlock, cupy-cuda11x, cupy-wheel
   Running setup.py install for cupy-wheel: started
   Running setup.py install for cupy-wheel: finished with status 'done'
 Successfully installed cupy-cuda11x-12.3.0 cupy-wheel-12.3.0 fastrlock-0.8.2
 Installing torch...
 Installing numpy...
 Installing einops...
 Installing opencv-contrib-python...
 Installing kornia...
 Installing scipy...
 Installing Pillow...
 Installing torchvision...
 Installing tqdm...
 Checking cupy...
 Uninstall cupy if existed...
 Installing cupy...
Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing Efficiency Nodes for ComfyUI Version 2.0+
Install custom node 'Efficiency Nodes for ComfyUI Version 2.0+'
Install: ['https://github.com/jags111/efficiency-nodes-comfyui']
Download: git clone 'https://github.com/jags111/efficiency-nodes-comfyui'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 793.0/793.0 [00:11<00:00, 68.55it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'clip-interrogator']
 Collecting clip-interrogator
   Downloading clip_interrogator-0.6.0-py3-none-any.whl (787 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 787.8/787.8 KB 8.1 MB/s eta 0:00:00
     Collecting open-clip-torch
   Downloading open_clip_torch-2.24.0-py3-none-any.whl (1.5 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 51.2 MB/s eta 0:00:00
    Collecting accelerate
   Downloading accelerate-0.29.3-py3-none-any.whl (297 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.6/297.6 KB 68.0 MB/s eta 0:00:00
                           Collecting sentencepiece
   Downloading sentencepiece-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 108.3 MB/s eta 0:00:00
 Collecting ftfy
   Downloading ftfy-6.2.0-py3-none-any.whl (54 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 KB 21.3 MB/s eta 0:00:00
 Collecting timm
   Downloading timm-0.9.16-py3-none-any.whl (2.2 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 130.2 MB/s eta 0:00:00
         Installing collected packages: sentencepiece, ftfy, accelerate, timm, open-clip-torch, clip-interrogator
 Successfully installed accelerate-0.29.3 clip-interrogator-0.6.0 ftfy-6.2.0 open-clip-torch-2.24.0 sentencepiece-0.2.0 timm-0.9.16

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'simpleeval']
 Collecting simpleeval
   Downloading simpleeval-0.9.13-py2.py3-none-any.whl (15 kB)
 Installing collected packages: simpleeval
 Successfully installed simpleeval-0.9.13
Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing FizzNodes
Install custom node 'FizzNodes'
Install: ['https://github.com/FizzleDorf/ComfyUI_FizzNodes']
Download: git clone 'https://github.com/FizzleDorf/ComfyUI_FizzNodes'
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 343.0/343.0 [00:00<00:00, 532.59it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'pandas']
     
## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'numexpr']
 Collecting numexpr
   Downloading numexpr-2.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (376 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.1/376.1 KB 5.6 MB/s eta 0:00:00
  Installing collected packages: numexpr
 Successfully installed numexpr-2.10.0
Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing ComfyUI_IPAdapter_plus
Install custom node 'ComfyUI_IPAdapter_plus'
Install: ['https://github.com/cubiq/ComfyUI_IPAdapter_plus']
Download: git clone 'https://github.com/cubiq/ComfyUI_IPAdapter_plus'
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 437.0/437.0 [00:00<00:00, 533.41it/s]
Installation was successful.

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'insightface']
 Collecting insightface
   Downloading insightface-0.7.3.tar.gz (439 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 KB 5.9 MB/s eta 0:00:00
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'done'
   Installing backend dependencies: started
   Installing backend dependencies: finished with status 'done'
   Preparing metadata (pyproject.toml): started
   Preparing metadata (pyproject.toml): finished with status 'done'
   Collecting onnx
   Downloading onnx-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 78.6 MB/s eta 0:00:00
 Collecting cython
   Using cached Cython-3.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
 Collecting albumentations
   Downloading albumentations-1.4.4-py3-none-any.whl (150 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.4/150.4 KB 49.7 MB/s eta 0:00:00
    Collecting prettytable
   Downloading prettytable-3.10.0-py3-none-any.whl (28 kB)
   Collecting scikit-learn
   Downloading scikit_learn-1.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 92.5 MB/s eta 0:00:00
 Collecting easydict
   Downloading easydict-1.13-py3-none-any.whl (6.8 kB)
 Collecting numpy
   Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
 Collecting pydantic>=2.6.4
   Downloading pydantic-2.7.1-py3-none-any.whl (409 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.3/409.3 KB 83.0 MB/s eta 0:00:00
          Collecting joblib>=1.2.0
   Downloading joblib-1.4.0-py3-none-any.whl (301 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.2/301.2 KB 71.6 MB/s eta 0:00:00
 Collecting threadpoolctl>=2.0.0
   Downloading threadpoolctl-3.4.0-py3-none-any.whl (17 kB)
             Collecting pydantic-core==2.18.2
   Downloading pydantic_core-2.18.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 130.3 MB/s eta 0:00:00
 Collecting annotated-types>=0.4.0
   Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
  Building wheels for collected packages: insightface
   Building wheel for insightface (pyproject.toml): started
   Building wheel for insightface (pyproject.toml): finished with status 'done'
   Created wheel for insightface: filename=insightface-0.7.3-cp310-cp310-linux_x86_64.whl size=1054128 sha256=c0d626be10e2aaff7d6b69000254ebdbf72845a7829d224d8ddf071d4147dc51
   Stored in directory: /root/.cache/pip/wheels/e3/d0/80/e3773fb8b6d1cca87ea1d33d9b1f20a223a6493c896da249b5
 Successfully built insightface
 Installing collected packages: easydict, threadpoolctl, pydantic-core, prettytable, numpy, joblib, cython, annotated-types, pydantic, onnx, scikit-learn, albumentations, insightface
   Attempting uninstall: numpy
     Found existing installation: numpy 1.24.1
     Uninstalling numpy-1.24.1:
       Successfully uninstalled numpy-1.24.1
   Attempting uninstall: pydantic
     Found existing installation: pydantic 1.10.9
     Uninstalling pydantic-1.10.9:
       Successfully uninstalled pydantic-1.10.9
 Successfully installed albumentations-1.4.4 annotated-types-0.6.0 cython-3.0.10 easydict-1.13 insightface-0.7.3 joblib-1.4.0 numpy-1.26.4 onnx-1.16.0 prettytable-3.10.0 pydantic-2.7.1 pydantic-core-2.18.2 scikit-learn-1.4.2 threadpoolctl-3.4.0
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing ComfyUI-Advanced-ControlNet
Install custom node 'ComfyUI-Advanced-ControlNet'
Install: ['https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet']
Download: git clone 'https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet'
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 428.0/428.0 [00:00<00:00, 584.10it/s]
Install: pip packages
Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing AnimateDiff Evolved
Install custom node 'AnimateDiff Evolved'
Install: ['https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved']
Download: git clone 'https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1254.0/1254.0 [00:00<00:00, 1685.41it/s]
Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing ComfyUI-VideoHelperSuite
Install custom node 'ComfyUI-VideoHelperSuite'
Install: ['https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite']
Download: git clone 'https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 765.0/765.0 [00:00<00:00, 1129.71it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'opencv-python']
  
## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'imageio-ffmpeg']
  Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:Installing Steerable Motion
Install custom node 'Steerable Motion'
Install: ['https://github.com/banodoco/steerable-motion']
Download: git clone 'https://github.com/banodoco/steerable-motion'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 440.0/440.0 [00:05<00:00, 77.96it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/Dough/dough-env/bin/python3', '-m', 'pip', 'install', 'matplotlib']
           Installation was successful.
After restarting ComfyUI, please refresh the browser.
DEBUG:app_logger:checking file: 
INFO:app_logger:Downloading ip-adapter-plus_sd15.bin
154340it [00:04, 30957.46it/s]█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 157M/158M [00:04<00:00, 36.5MB/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 158M/158M [00:05<00:00, 31.0MB/s]
DEBUG:app_logger:checking file: 
INFO:app_logger:Downloading pytorch_model.bin
2469221it [00:23, 106499.95it/s]██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 2.52G/2.53G [00:23<00:00, 110MB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.53G/2.53G [00:23<00:00, 109MB/s]
DEBUG:app_logger:checking file: 
INFO:app_logger:Downloading pytorch_model.bin
3603626it [00:35, 102529.82it/s]██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 3.68G/3.69G [00:35<00:00, 116MB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.69G/3.69G [00:35<00:00, 105MB/s]
DEBUG:app_logger:checking file: 
INFO:app_logger:Downloading vae-ft-mse-840000-ema-pruned.safetensors
326799it [00:03, 100383.47it/s]█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 333M/335M [00:03<00:00, 110MB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:03<00:00, 103MB/s]
DEBUG:app_logger:checking file: 
INFO:app_logger:Downloading Deliberate_v2.safetensors
2082650it [00:59, 34969.65it/s]██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 2.13G/2.13G [00:59<00:00, 33.7MB/s]
INFO:app_logger:Error generating output [Errno 28] No space left on device
Traceback (most recent call last):
  File "/Dough/comfy_runner/inf.py", line 360, in predict
    res_models = self.download_models(workflow, extra_models_list, ignore_model_list)
  File "/Dough/comfy_runner/inf.py", line 201, in download_models
    status, similar_models, file_status = self.model_downloader.download_model(model)
  File "/Dough/comfy_runner/utils/file_downloader.py", line 153, in download_model
    _, file_status = self.download_file(
  File "/Dough/comfy_runner/utils/file_downloader.py", line 73, in download_file
    tar_ref.extractall(dest)
  File "/usr/lib/python3.10/tarfile.py", line 2257, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2324, in _extract_one
    self._handle_fatal_error(e)
  File "/usr/lib/python3.10/tarfile.py", line 2320, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2403, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2456, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.10/tarfile.py", line 255, in copyfileobj
    dst.write(buf)
OSError: [Errno 28] No space left on device

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.13G/2.13G [01:00<00:00, 35.5MB/s]
DEBUG:app_logger:Process 1823 (Port 4333)
error occured:  'file_paths'
Traceback (most recent call last):
  File "/Dough/banodoco_runner.py", line 313, in check_and_update_db
    output = predict_gpu_output(data['workflow_input'], data['file_path_list'], \
  File "/Dough/utils/ml_processor/gpu/utils.py", line 36, in predict_gpu_output
    return output['file_paths']   # ignoring text output for now {"file_paths": [], "text_content": []}
KeyError: 'file_paths'
Traceback (most recent call last):
  File "/Dough/banodoco_runner.py", line 313, in check_and_update_db
    output = predict_gpu_output(data['workflow_input'], data['file_path_list'], \
  File "/Dough/utils/ml_processor/gpu/utils.py", line 36, in predict_gpu_output
    return output['file_paths']   # ignoring text output for now {"file_paths": [], "text_content": []}
KeyError: 'file_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Dough/banodoco_runner.py", line 381, in <module>
    main()
  File "/Dough/banodoco_runner.py", line 99, in main
    check_and_update_db()
  File "/Dough/banodoco_runner.py", line 347, in check_and_update_db
    InferenceLog.objects.filter(id=log.id).update(status=InferenceStatus.FAILED.value)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/query.py", line 1206, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1982, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 616, in execute
    return real_execute(self, sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Dough/dough-env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: unable to open database file

**Comment by piyushK52** [comment]
let me know a couple of things
1. in which drive have you setup dough ? (C: , D: , E: ...)
2. is there a file called banodoco_local.db inside the Dough folder ?

**Comment by Jamieharley** [comment]
Thanks for your help :)
I run it with Runpod, the installation is in workspace/dough and there is no banodoco_local.db in the folder.

**Comment by piyushK52** [comment]
This is the error - OSError: [Errno 28] No space left on device 😅.. start a new pod and edit its storage to be 150 gb (just to be safe).. increasing storage of the pod doesn’t cost anything extra

**Comment by piyushK52** [comment]
let me know if that worked, closing this issue for now

**Comment by piyushK52** [comment]
there was a change in this node a couple of days back, I have pushed a fix for this.. close the app and run "git pull origin main" inside the repo (if this doesn't work then try a fresh install)... let me know if that works

**Comment by Jamieharley** [comment]
it's now working :) Thank you!
