### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mischaschaub** [banodoco/Dough#141]
[error.txt](https://github.com/banodoco/Dough/files/15209127/error.txt)
On a 3090 with 24 GB VRAM I get this error often. What can I do about this?

**Comment by piyushK52** [comment]
I think you cancelled some of the downloads before completion and it resulted in corrupted files

**Comment by mischaschaub** [comment]
Thank you, will reinstall the lot. This should be rather easy, as I use dough as a part of Visions of Chaos.
