### ISSUE TITLE
Analogue Drag/Drop

### ISSUE THREAD

**Issue by mischaschaub** [banodoco/Dough#142]
Might be helpful, if the interface for arranging images in shots and shots in sequences would be more analogue, as users know and estimate this.  So the relative duration of an element should be shown by repeating the image, and mixing two sequences could be shown by overlaps etc.  And dragging and dropping an element might be better than using arrows. Not urgent, I agree, but please consider.

**Comment by peteromallet** [comment]
Hi @mischaschaub, yeah, we will add lots of better interaction methods soon and in a successor app - thanks for your suggestion!
