### ISSUE TITLE
getting error trying to run (are these errors major?)

### ISSUE THREAD

**Issue by xx88xx** [banodoco/Dough#171]
Are these errors causing major errors? It seems to be taking forever to run with utilisastion mostly on my cpu and ram. 
Not sure if I need to adjust my settings or my install didn't work out properly?

Here's what the terminal says:

~/Dough# ./scripts/entrypoint.sh

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:5500
  Network URL: http://xx.xxx.xxx.xx.:5500

INFO:app_logger:Starting runner
runner running
DEBUG:app_logger:cloning comfy repo
DEBUG:app_logger:Checking comfy requirements, please wait...
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-31 05:41:57.978405
** Platform: Linux
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
** Python executable: /root/Dough/dough-env/bin/python3
** Log path: /root/Dough/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11264 MB, total RAM 23976 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Making the "web\extensions\FizzleDorf" folder
Update to javascripts files detected
Copying Folder here to satisfy init, eventually I'll have stuff in here..txt to extensions folder
Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
FizzleDorf Custom Nodes: Loaded
### ComfyUI Revision: 2218 [bf3e334d] | Released on '2024-05-30'

Import times for custom nodes:
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_essentials
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.3 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.3 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.4 seconds: /root/Dough/ComfyUI/custom_nodes/steerable-motion
   0.4 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite

Starting server

To see the GUI go to: http://127.0.0.1:4333
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
DEBUG:app_logger:Process 11959 (Port 4333)
DEBUG:app_logger:comfy server is running
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json [DONE]
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/github-stats.json [DONE]
Update check done.
DEBUG:app_logger:checking file:
INFO:app_logger:Downloading film_net_fp32.pt
134690it [00:11, 11347.05it/s]██████████████████████████████████████████████████████▍| 137M/138M [00:11<00:00, 10.2MB/s]
100%|████████████████████████████████████████████████████████████████████████████████| 138M/138M [00:11<00:00, 11.6MB/s]
INFO:app_logger:Restarting the server
DEBUG:app_logger:Process 11959 (Port 4333)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-31 05:42:19.836052
** Platform: Linux
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
** Python executable: /root/Dough/dough-env/bin/python3
** Log path: /root/Dough/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11264 MB, total RAM 23976 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
FizzleDorf Custom Nodes: Loaded
### ComfyUI Revision: 2218 [bf3e334d] | Released on '2024-05-30'

Import times for custom nodes:
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /root/Dough/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.1 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.3 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.3 seconds: /root/Dough/ComfyUI/custom_nodes/steerable-motion
   0.4 seconds: /root/Dough/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite

Starting server

To see the GUI go to: http://127.0.0.1:4333
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
DEBUG:app_logger:Process 12070 (Port 4333)
DEBUG:app_logger:comfy server is running
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
DEBUG:app_logger:Updating ip-adapter-plus_sd15.bin to ip-adapter-plus_sd15.bin
DEBUG:app_logger:Updating pytorch_model.bin to SD1.5/pytorch_model.bin
DEBUG:app_logger:Updating vae-ft-mse-840000-ema-pruned.safetensors to vae-ft-mse-840000-ema-pruned.safetensors
DEBUG:app_logger:Updating Realistic_Vision_V5.1.safetensors to Realistic_Vision_V5.1.safetensors
DEBUG:app_logger:Updating v3_sd15_sparsectrl_rgb.ckpt to SD1.5/animatediff/v3_sd15_sparsectrl_rgb.ckpt
DEBUG:app_logger:Updating v3_sd15_mm.ckpt to v3_sd15_mm.ckpt
INFO:app_logger:Generating output please wait
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
WARNING: Sequential prompt keyframes 5:100 and 6:96 are not monotonously increasing; skipping interpolation.
WARNING: Sequential prompt keyframes 5:100 and 6:96 are not monotonously increasing; skipping interpolation.
Requested to load SD1ClipModel
Loading 1 new model
WARNING: Sequential prompt keyframes 5:100 and 6:96 are not monotonously increasing; skipping interpolation.
WARNING: Sequential prompt keyframes 5:100 and 6:96 are not monotonously increasing; skipping interpolation.
Requested to load CLIPVisionModelProjection
Loading 1 new model
[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt via Gen2
!!! Exception during processing!!! PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "/root/Dough/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/Dough/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/Dough/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/nodes_gen2.py", line 178, in load_motion_model
    motion_model = load_motion_module_gen2(model_name=model_name, motion_model_settings=ad_settings)
  File "/root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_injection.py", line 1081, in load_motion_module_gen2
    mm_state_dict = comfy.utils.load_torch_file(model_path, safe_load=True)
  File "/root/Dough/ComfyUI/comfy/utils.py", line 21, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
  File "/root/Dough/dough-env/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/Dough/dough-env/lib/python3.10/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Prompt executed in 38.33 seconds
DEBUG:app_logger:output file list len: 0
DEBUG:app_logger:Process 12070 (Port 4333)
error occured:  list index out of range
Traceback (most recent call last):
  File "/root/Dough/banodoco_runner.py", line 373, in check_and_update_db
    res_output = format_model_output(output, log.model_name)
  File "/root/Dough/banodoco_runner.py", line 217, in format_model_output
    return [output[-1]]
IndexError: list index out of range
DEBUG:app_logger:cloning comfy repo
DEBUG:app_logger:Checking comfy requirements, please wait...
DEBUG:app_logger:Process 12070 (Port 4333)
DEBUG:app_logger:Process 12070 (Port 4333)
DEBUG:app_logger:Server already running
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json [DONE]
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/github-stats.json [DONE]
Update check done.
DEBUG:app_logger:Updating ip-adapter-plus_sd15.bin to ip-adapter-plus_sd15.bin
DEBUG:app_logger:Updating pytorch_model.bin to SD1.5/pytorch_model.bin
DEBUG:app_logger:Updating vae-ft-mse-840000-ema-pruned.safetensors to vae-ft-mse-840000-ema-pruned.safetensors
DEBUG:app_logger:Updating Realistic_Vision_V5.1.safetensors to Realistic_Vision_V5.1.safetensors
DEBUG:app_logger:Updating v3_sd15_sparsectrl_rgb.ckpt to SD1.5/animatediff/v3_sd15_sparsectrl_rgb.ckpt
DEBUG:app_logger:Updating v3_sd15_mm.ckpt to v3_sd15_mm.ckpt
INFO:app_logger:Generating output please wait
got prompt
[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt via Gen2
!!! Exception during processing!!! PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "/root/Dough/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/Dough/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/Dough/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/nodes_gen2.py", line 178, in load_motion_model
    motion_model = load_motion_module_gen2(model_name=model_name, motion_model_settings=ad_settings)
  File "/root/Dough/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_injection.py", line 1081, in load_motion_module_gen2
    mm_state_dict = comfy.utils.load_torch_file(model_path, safe_load=True)
  File "/root/Dough/ComfyUI/comfy/utils.py", line 21, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
  File "/root/Dough/dough-env/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/Dough/dough-env/lib/python3.10/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Prompt executed in 13.05 seconds
DEBUG:app_logger:output file list len: 0
DEBUG:app_logger:Process 12070 (Port 4333)
error occured:  list index out of range
Traceback (most recent call last):
  File "/root/Dough/banodoco_runner.py", line 373, in check_and_update_db
    res_output = format_model_output(output, log.model_name)
  File "/root/Dough/banodoco_runner.py", line 217, in format_model_output
    return [output[-1]]
IndexError: list index out of range
FETCH DATA from: /root/Dough/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]

**Comment by piyushK52** [comment]
I think you interrupted the download process in your previous runs.. if possible try doing a fresh install or deleting the models present inside comfy
