### ISSUE TITLE
How to Generate Sequences?

### ISSUE THREAD

**Issue by 6630507** [banodoco/Dough#180]
I've figured out how to load images into the UI and add them to the queue, but as far as I can tell, the only way to execute the queue is to stop the server and re-launch it.  Is there something I'm missing?

**Comment by piyushK52** [comment]
I am not sure if i understand your question correctly, but we will be putting out a proper explainer video soon. You can check this quick setup vid in the meantime https://www.youtube.com/watch?v=L7f4Ui3DVsM . Also if you can share a screen recording of the dough app, pointing out the issue, we will be able to guide you better
